version: "3.9"
   
services:
    django_database:
        build: ./docker/mysql
        image: "mysql:${PROJECT_NAME}"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - django-database:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=django
            - MYSQL_USER=djangouser
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        cap_add:
            - SYS_NICE
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
            interval: 5s
            timeout: 10s
            retries: 40
    nginx:
        build: ./docker/nginx
        image: "nginx:${PROJECT_NAME}"
        ports:
        - "127.0.0.1:${NGINX_PORT}:80"
        depends_on:
        - django
        volumes:
        - ./docker/nginx/config:/etc/nginx/conf.d:ro
        - ./static:/static
        - ./media:/media
    django:
        user: djangouser
        image: "python:${PROJECT_NAME}"
        command: bash -c "
            python manage.py makemigrations && 
            python manage.py migrate && 
            python manage.py collectstatic --noinput && 
            gunicorn --bind :8000 ${PROJECT_NAME}.wsgi"
        volumes:
            - ".:/${PROJECT_NAME}"
        depends_on:
            django_database:
                condition: service_healthy

volumes:
    django-database: